### ISSUE TITLE
LEDs in the schematic

### ISSUE THREAD

**Issue by Solartraveler** [Wer-Wolf/Morse-Cache#1]
Hi,
looking at
https://github.com/Wer-Wolf/Morse-Cache/releases/download/release2.0/Circuit.pdf
Are the LEDs in the wrong direction or should the GND be a Vcc symbol?

**Comment by Wer-Wolf** [comment]
Yes, it seems that i indeed swaped the LED's direction, the GND symbol is correct.
I will update the circuit soon.

**Comment by Wer-Wolf** [comment]
The updated schematic is available under the 2.0 release.
Thank you.
